pipeline{
    agent{ node { label 'buildfarm'}}
    stages{
        stage('scm checkout'){
            steps{
                sh'echo 'pulled the code from scm''
            }
        }
        stage('load properties file'){
            steps{
                sh'echo 'loaded properties file''
            }

        }
        
    }

}
