pipeline{

    agent {node {label 'buildfarm'}}

    stages{
        stage('Git Repo'){
            steps{
                sh 'git Pclone "https://github.com/Tinesh379/time-tracker.git"'
            }
        }
        stage('Build'){
            steps{
               sh 'cd ${workspace}/maven-pipeline/time-tracker'
                sh 'mvn clean package'
            }
        }
    }
    post{
        always{
            cleanWs()
        }
    }
}