pipeline{

    agent {node {label 'buildfarm'}}

    stages{
        stage('Git Repo'){
            steps{
                sh 'git clone "https://github.com/Tinesh379/Hello-World.git"'
                           }
        }
        stage('Build'){
            steps{
                sh "echo '${WORKSPACE}'" 
                sh "cd ${WORKSPACE}/Hello-World"
                sh 'mvn clean package'
            }
        }
    }
    post{
        always{
            cleanWs()
        }
    }
}
