pipeline{

    agent {node {label 'buildfarm'}}

    stages{
        stage('Git Repo'){
            steps{
                sh 'git clone "https://github.com/Tinesh379/time-tracker.git"'
            }
        }
        stage('Build'){
            steps{
                sh "echo '${WORKSPACE}'" 
                //sh 'mvn clean package'
            }
        }
    }
    post{
        always{
            cleanWs()
        }
    }
}
